# Cleans up files when a new template-based repo is created

name: Template Cleanup
on:
  push:
    branches:
      - main
jobs:
  template-cleanup:
    name: Template Cleanup
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'next-markdown-blog-starter'
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
